services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret # Élesben ezt a Portainerből add át biztonságosan!
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_prod_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootsecret"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
  backend:
    image: ghcr.io/sunrab1822/szevent-backend:v1.0.5
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: production
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    restart: always
  scheduler:
    image: ghcr.io/sunrab1822/szevent-backend:v1.0.5 # Ugyanaz a kép, mint a backend
    command: ["scheduler"]
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    environment:
      APP_ENV: production
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    restart: unless-stopped
  frontend:
    image: ghcr.io/sunrab1822/szevent-frontend:v1.0.5
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
volumes:
  db_prod_data:
