import { SetSelectedEvent } from "../redux/action/events/setSelectedEvent";
import { store } from "../redux/store";

export const getEvent = async (id: number): Promise<boolean> => {
    // const event = {
    //     id: 1,
    //     name: "Megadnak neki valamiért ilyen nagyon hosszú nevet",
    //     description: "",
    //     location: "string",
    //     address: "string",
    //     startDate: "2026-04-07 19:41:13",
    //     endDate: "2026-04-09 19:41:13",
    //     type: "string",
    //     qualification: 0,
    //     participants: 1,
    //     public: "string",
    //     nature: "string",
    //     detailedProgramPlan: "string",
    //     furnishedMethod: "string",
    //     needAccommodation: false,
    //     needAccommodationNumber: 0,
    //     needParkingSpace: true,
    //     needParkingSpaceNumber: 0,
    //     producesTrash: true,
    //     producesTrashDelivery: "other",
    //     producesTrashDeliveryWhoDelivers: "string",
    //     needWifi: true,
    //     needEducationalTechnology: true,
    //     needEducationalTechnologyItems: "string",
    //     participantsWithReducedMobility: true,
    //     willBePhotos: true,
    //     willBePhotosDevice: "string",
    //     needCatering: true,
    //     needCateringType: ["item1", "item2"],
    //     willBeConstruction: true,
    //     constructionStartDate: "2026-04-07 07:00:00",
    //     constructionEndDate: "2026-04-08 08:00:00",
    //     constructionSubcontractors: "string",
    //     constructionInHeights: true,
    //     constructionNeedScaffolding: true,
    //     constructionManualMaterialHandling: true,
    //     constructionMechanicalMaterialHandling: true,
    //     constructionMechanicalMaschines: "string",
    //     constructionMechanicalMaschinesOthers: "string",
    //     needCleaningBefore: true,
    //     needCleaningDuringEvent: true,
    //     needElectricians: "string",
    //     needElectricityFromCabinet: true,
    //     needElectricityFromCabinetNumber: "string",
    //     fireHazardExpected: true,
    //     fireHazardExpectedDescription: "string",
    //     expectedDustSmokeVapor: "string",
    //     expectedUsageOfChemicals: true,
    //     expectedUsageOfChemicalsDescription: "string",
    //     expectedDecor: true,
    //     organizerFullName: "string",
    //     organizerPhone: "string",
    //     organizerEmail: "user@example.com",
    //     organizerAddress: "string",
    //     moreOrganizer: true,
    //     secondOrganizerFullName: "",
    //     secondOrganizerPhone: "string",
    //     secondOrganizerEmail: "user@example.com",
    //     secondOrganizerAddress: "string",
    //     customerWithLegalBackgroundName: "",
    //     customerWithLegalBackgroundAddress: "string",
    //     customerWithLegalBackgroundTaxNumber: "string",
    //     customerWithLegalBackgroundPhone: "string",
    //     customerWithLegalBackgroundEmail: "user@example.com",
    //     isBelso: false,
    //     status: "UF Árajánlatra vár",
    //     assignedUsers: [
    //         {
    //             id: 1,
    //             name: "Béla",
    //             email: "user@example.com",
    //             role_with_domain: "string",
    //             displayName: "string",
    //             picture: "https://placehold.co/40",
    //             role: 1,
    //             admin: true,
    //             token: "string",
    //             roleName: "string",
    //         },
    //         {
    //             id: 2,
    //             name: "Józsi",
    //             email: "user@example.com",
    //             role_with_domain: "string",
    //             displayName: "string",
    //             picture: "https://placehold.co/40",
    //             role: 1,
    //             admin: true,
    //             token: "string",
    //             roleName: "string",
    //         },
    //     ],
    //     statusChanges: [
    //         {
    //             from: "Beérkezett",
    //             to: "Beérkezett",
    //             events_id: 1,
    //             users_id: 0,
    //             timestamp: 1,
    //             username: "Rendszer",
    //             reason: null,
    //         },
    //         {
    //             from: "Beérkezett",
    //             to: "UF Árajánlatra vár",
    //             events_id: 1,
    //             users_id: 1,
    //             timestamp: 1,
    //             username: "Józsi",
    //             reason: null,
    //         },
    //         {
    //             from: "UF Árajánlatra vár",
    //             to: "UF Árajánlatra vár",
    //             events_id: 1,
    //             users_id: 1,
    //             timestamp: 1,
    //             username: "Józsi",
    //             reason: "Azért mert hát nem volt jó ez se meg az se meg amaz is rosszul van egyébként, szóval ez az egész így nem lesz jó, örülök, hogy próbálkoztál, de elcseszted, ez ilyen ez a lyatek.",
    //         },
    //     ],
    //     messages: [
    //         {
    //             id: 1,
    //             senderId: 1,
    //             username: "Józsi",
    //             timestamp: 1777035185,
    //             message: "Ez egy uzenet, amit tudok megadni",
    //         },
    //         {
    //             id: 2,
    //             senderId: 1,
    //             username: "Józsi",
    //             timestamp: 1777294385,
    //             message: "Nagyon nagyon vicci micci",
    //         },
    //         {
    //             id: 3,
    //             senderId: 2,
    //             username: "Béla",
    //             timestamp: 1777380785,
    //             message: "Hehe",
    //         },
    //         {
    //             id: 3,
    //             senderId: 2,
    //             username: "Béla",
    //             timestamp: 1777380790,
    //             message: "Hehe",
    //         },
    //         {
    //             id: 4,
    //             senderId: 3,
    //             username: "Irci",
    //             timestamp: 1777398785,
    //             message: "Vicces vagyok hihihi hehehe írok egy hosszú szöveget mert vicces vagyok, hihihih",
    //         },
    //         {
    //             id: 5,
    //             senderId: 1,
    //             username: "Józsi",
    //             timestamp: 1777398786,
    //             message: "Ez egy uzenet, amit tudok megadni ami hosszabb mert kitudja milyen hosszú üziket fognak itt írkodni",
    //         },
    //         {
    //             id: 6,
    //             senderId: 1,
    //             username: "Józsi",
    //             timestamp: 1777398800,
    //             message: "Valami üzi",
    //         },
    //     ],
    // };

    const response = await fetch(`${import.meta.env.VITE_API_ORIGIN}/api/event`, {
        headers: {
            Authorization: `Bearer ${localStorage.getItem(`${import.meta.env.VITE_AUTH_TOKEN}`)}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            id,
        }),
        method: "POST",
    });

    if (!response.ok) {
        return false;
    }

    const body = await response.json();
    store.dispatch(SetSelectedEvent({ selectedEvent: body.event[0] }));

    return true;
};
