import type { Status } from "./status";
import type { User } from "./user";

export interface Event {
    id: number;
    name: string;
    description: string;
    location: string;
    address: string;
    startDate: string;
    endDate: string;
    type: string;
    qualification: number;
    participants: number;
    public: string;
    nature: string;
    detailedProgramPlan: string;
    furnishedMethod: string;
    needAccommodation: boolean;
    needAccommodationNumber: number;
    needParkingSpace: boolean;
    needParkingSpaceNumber: number;
    producesTrash: boolean;
    producesTrashDelivery: string;
    producesTrashDeliveryWhoDelivers: string;
    needWifi: boolean;
    needEducationalTechnology: boolean;
    needEducationalTechnologyItems: string;
    participantsWithReducedMobility: boolean;
    willBePhotos: boolean;
    willBePhotosDevice: string;
    needCatering: boolean;
    needCateringType: string[];
    willBeConstruction: boolean;
    constructionStartDate: string;
    constructionEndDate: string;
    constructionSubcontractors: string;
    constructionInHeights: boolean;
    constructionNeedScaffolding: boolean;
    constructionManualMaterialHandling: boolean;
    constructionMechanicalMaterialHandling: boolean;
    constructionMechanicalMaschines: string;
    constructionMechanicalMaschinesOthers: string;
    needCleaningBefore: boolean;
    needCleaningDuringEvent: boolean;
    needElectricians: string;
    needElectricityFromCabinet: boolean;
    needElectricityFromCabinetNumber: string;
    fireHazardExpected: boolean;
    fireHazardExpectedDescription: string;
    expectedDustSmokeVapor: string;
    expectedUsageOfChemicals: boolean;
    expectedUsageOfChemicalsDescription: string;
    expectedDecor: boolean;
    organizerFullName: string;
    organizerPhone: string;
    organizerEmail: string;
    organizerAddress: string;
    moreOrganizer: boolean;
    secondOrganizerFullName: string;
    secondOrganizerPhone: string;
    secondOrganizerEmail: string;
    secondOrganizerAddress: string;
    customerWithLegalBackgroundName: string;
    customerWithLegalBackgroundAddress: string;
    customerWithLegalBackgroundTaxNumber: string;
    customerWithLegalBackgroundPhone: string;
    customerWithLegalBackgroundEmail: string;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    status: string;
    rejectReason: string | null;
    famulusPrice: null;
    dormPrice: null;
    uniPrice: null;
    assigned_user: User[] | [];
    status_changes: Status[] | [];
    messages: {
        id: number;
        senderId: number;
        username: string;
        message: string;
        timestamp: number;
    }[];
    unSeen: boolean;
}
